//! PT-Depiler canonical site identifiers keyed by their known host names.
//!
//! Generated from PT-Depiler site definitions at commit
//! `e9fae952f8200ed06a0822baae6f6f6ae84b2f5a` (2026-08-31).

pub fn site_id_for_host(host: &str) -> Option<&'static str> {
    let host = host.trim_end_matches('.');
    let host = host.strip_prefix("www.").unwrap_or(host);
    match host {
        "0cili.com" | "0cili.my" | "0mag.net" | "0magnet.com" | "13mag.net" | "16mag.net"
        | "1cili.com" | "6mag.net" | "7mag.net" | "8ci.li" | "9mag.net" | "cili.info"
        | "cili.uk" | "getmag.net" | "wuji.me" | "xcili.net" => Some("0magnet"),
        "1337x.abcproxy.org"
        | "1337x.gd"
        | "1337x.is"
        | "1337x.mrunblock.bond"
        | "1337x.ninjaproxy1.com"
        | "1337x.proxyninja.net"
        | "1337x.proxyninja.org"
        | "1337x.so"
        | "1337x.st"
        | "1337x.to"
        | "1337x.torrentbay.st"
        | "1337x.torrentsbay.org"
        | "1337x.unblockit.download"
        | "1337x.unblockninja.com"
        | "x1337x.cc"
        | "x1337x.eu"
        | "x1337x.se"
        | "x1337x.ws" => Some("1337x"),
        "13city.online" | "13city.org" => Some("13city"),
        "1ptba.com" => Some("1ptba"),
        "pt.2xfree.org" => Some("2xfree"),
        "52movie.top" => Some("52movie"),
        "52pt.site" => Some("52pt"),
        "acg.rip" => Some("acgrip"),
        "ptlover.cc" => Some("afun"),
        "agsvpt.com" | "new.agsvpt.cn" | "pt.agsvpt.cn" => Some("agsvpt"),
        "aidoru-online.me" => Some("aidoruonline"),
        "aither.cc" => Some("aither"),
        "pt.aling.de" => Some("alingpt"),
        "alpharatio.cc" => Some("alpharatio"),
        "animebytes.tv" => Some("animebytes"),
        "animelovers.club" => Some("animelovers"),
        "animetosho.org" => Some("animetosho"),
        "animez.to" => Some("animez"),
        "anirena.com" => Some("anirena"),
        "asnet.pw" => Some("anisource"),
        "anthelion.me" => Some("anthelion"),
        "asiancinema.me" | "eiga.moi" => Some("asiancinema"),
        "asmrpt.org" => Some("asmrpt"),
        "audiences.me" => Some("audiences"),
        "audiobookbay.fi" | "audiobookbay.is" | "audiobookbay.lu" | "audiobookbay.se"
        | "audiobookbay.ws" | "theaudiobookbay.se" => Some("audiobookbay"),
        "audionews.org" => Some("audionews"),
        "aura4k.net" => Some("aura4k"),
        "avgv.cc" => Some("avgv"),
        "avistaz.to" => Some("avistaz"),
        "awesome-hd.me" => Some("awesomehd"),
        "azusa.wiki" => Some("azusa"),
        "baconbits.org" => Some("baconbits"),
        "bakabt.me" => Some("bakabt"),
        "p.t-baozi.cc" => Some("baozi"),
        "beitai.pt" => Some("beitai"),
        "beyond-hd.me" => Some("beyondhd"),
        "bitporn.eu" => Some("bitporn"),
        "bitpt.cn" => Some("bitpt"),
        "blutopia.cc" | "blutopia.xyz" => Some("blutopia"),
        "broadcasthe.net" => Some("broadcasthenet"),
        "brokenstones.is" => Some("brokenstones"),
        "bt.etree.org" => Some("btetree"),
        "pt.btschool.club" | "pt.btschool.net" => Some("btschool"),
        "bt.byr.cn" | "byr.pt" => Some("byrbt"),
        "capybarabr.com" => Some("capybarabr"),
        "carpt.net" => Some("carpt"),
        "cathode-ray.tube" => Some("cathoderaytube"),
        "cangbao.ge" => Some("cbg"),
        "ccfbits.org" => Some("ccfbits"),
        "pt.cdfile.org" => Some("cdfile"),
        "pt.cdy.pics" | "pt.cdy.skin" => Some("cdy"),
        "cgpeers.com" | "cgpeers.to" => Some("cgpeers"),
        "chdbits.co" | "ptchdbits.co" => Some("chdbits"),
        "cinemageddon.net" => Some("cinemageddon"),
        "cinematik.net" => Some("cinematik"),
        "cinemaz.to" => Some("cinemaz"),
        "clearjav.com" => Some("clearjav"),
        "cnlang.org" => Some("cnlang"),
        "cnscg.club" | "hdscg.cc" => Some("cnscg"),
        "crabpt.vip" => Some("crabpt"),
        "cspt.cc" | "cspt.date" | "cspt.top" => Some("cspt"),
        "cyanbug.net" => Some("cyanbug"),
        "dajiao.cyou" => Some("dajiao"),
        "darkpeers.org" => Some("darkpeers"),
        "pt.daxiangjiao.org" => Some("daxiangjiao"),
        "desigaane.rocks" => Some("desigaane"),
        "pt.dhtclub.com" => Some("dhtclub"),
        "dicmusic.club" | "dicmusic.com" => Some("dicmusic"),
        "digitalcore.club" => Some("digitalcore"),
        "discfan.net" | "pt.gztown.net" => Some("discfan"),
        "share.dmhy.org" => Some("dmhy"),
        "dragonhd.xyz" => Some("dragonhd"),
        "dstudio.me" => Some("dstudio"),
        "dubhe.site" => Some("dubhe"),
        "dxdhd.com" => Some("dxdhd"),
        "ecustpt.eu.org" | "pt.ecust.pp.ua" | "public.ecustpt.eu.org" => Some("ecustpt"),
        "e-hentai.org" | "exhentai.org" => Some("ehentai"),
        "emparadise.rs" | "empornium.is" | "empornium.me" | "empornium.rs" | "empornium.sx" => {
            Some("empornium")
        }
        "exoticaz.to" | "torrents.yourexotic.com" => Some("exoticaz"),
        "ext.to" | "extranet.torrentbay.st" | "search.extto.com" => Some("exttorrents"),
        "fearnopeer.com" => Some("fearnopeer"),
        "pt.521.best" => Some("fhpt"),
        "filelist.io" | "flro.org" => Some("filelist"),
        "filept.com" => Some("filept"),
        "pt.0ff.cc" => Some("freefarm"),
        "fsm.name" => Some("fsm"),
        "gainbound.net" => Some("gainbound"),
        "gazellegames.net" => Some("gazellegames"),
        "gfxpeers.net" => Some("gfxpeers"),
        "gamegamept.com" => Some("ggpt"),
        "greatposterwall.com" => Some("greatposterwall"),
        "gay-torrents.net" => Some("gtnet"),
        "gay-torrents.org" => Some("gtorg"),
        "gaytor.rent" | "gaytorrent.ru" => Some("gtru"),
        "haidan.cc" | "haidan.video" => Some("haidan"),
        "happyfappy.net" | "happyfappy.org" => Some("happyfappy"),
        "club.hares.top" => Some("hares"),
        "pt.hd4fans.org" => Some("hd4fans"),
        "hd4.xyz" => Some("hd4free"),
        "hd.ai" => Some("hdai"),
        "hdarea.club" | "hdarea.co" => Some("hdarea"),
        "hdatmos.club" => Some("hdatmos"),
        "hdbao.cc" => Some("hdbao"),
        "hdbits.org" => Some("hdbits"),
        "hdchina.org" => Some("hdchina"),
        "hdcity.city" | "hdcity.leniter.org" | "hdcity.top" | "hdcity.work" => Some("hdcity"),
        "pt.hdclone.org" | "pt.hdclone.top" => Some("hdclone"),
        "hddisk.org" => Some("hddisk"),
        "hddolby.com" => Some("hddolby"),
        "hdf.world" => Some("hdf"),
        "hdfans.org" => Some("hdfans"),
        "hdhome.org" => Some("hdhome"),
        "cf.hdkylin.com" | "hdkyl.in" | "na.hdkylin.com" => Some("hdkylin"),
        "hdmayi.com" => Some("hdmayi"),
        "pt.hdpost.top" => Some("hdpost"),
        "hdpt.xyz" => Some("hdpt"),
        "hdroute.org" => Some("hdroute"),
        "hdsky.me" => Some("hdsky"),
        "hd-space.org" => Some("hdspace"),
        "hdstreet.club" => Some("hdstreet"),
        "hdtime.org" => Some("hdtime"),
        "hd-torrents.me" | "hd-torrents.net" | "hd-torrents.org" | "hdts.ru" => Some("hdtorrents"),
        "pt.hdupt.com" | "pt.upxin.net" => Some("hdupt"),
        "hdvideo.one" | "hdvideo.top" => Some("hdvideo"),
        "hdfun.me" | "hdzone.me" => Some("hdzone"),
        "hhanclub.net" | "hhanclub.top" => Some("hhanclub"),
        "hitpt.com" | "pt.ghtt.net" => Some("hitpt"),
        "hspt.club" => Some("hspt"),
        "htpt.cc" => Some("htpt"),
        "hudbt.hust.edu.cn" => Some("hudbt"),
        "hawke.uno" | "hawke.unoz" => Some("huno"),
        "hxpt.org" => Some("hxpt"),
        "ianon.app" => Some("ianon"),
        "icc2022.com" => Some("icc2022"),
        "ihdbits.me" | "pt.newworld.plus" => Some("ihdbits"),
        "mua.xloli.cc" | "share.ilolicon.com" => Some("ilolicon"),
        "iptorrents.com" => Some("iptorrents"),
        "pt.itzmx.com" => Some("itzmx"),
        "joyhd.net" => Some("joyhd"),
        "jpopsuki.eu" => Some("jpopsuki"),
        "jptv4.us" => Some("jptv4us"),
        "jptv.club" => Some("jptvclub"),
        "kamept.com" => Some("kamept"),
        "karagarga.in" => Some("karagarga"),
        "pt.keepfrds.com" => Some("keepfrds"),
        "our.kelu.one" => Some("kelu"),
        "kimoji.club" => Some("kimoji"),
        "kufei.org" => Some("kufei"),
        "kufirc.com" => Some("kufirc"),
        "yhpp.cc" => Some("kunlun"),
        "pt.lajidui.top" => Some("lajidui"),
        "lat-team.com" => Some("latteam"),
        "lemonhd.club" => Some("lemonhd"),
        "lemonhd.net" => Some("lemonhdnet"),
        "leaguehd.com" | "lemonhd.org" => Some("lemonhdorg"),
        "longpt.org" | "wiiii.dpdns.org" => Some("longpt"),
        "lst.gg" => Some("lst"),
        "pt.luckpt.de" => Some("luckpt"),
        "luminarr.me" => Some("luminarr"),
        "duckboobee.org" | "marchcms.org" => Some("march"),
        "midnightscene.cc" => Some("midnightscene"),
        "milkie.cc" => Some("milkie"),
        "mine.pt" => Some("minept"),
        "moecat.best" => Some("moecat"),
        "momentpt.top" => Some("momentpt"),
        "monikadesign.uk" => Some("monikadesign"),
        "mooko.org" => Some("mooko"),
        "morethan.tv" | "morethantv.me" => Some("morethantv"),
        "ap.m-team.cc" | "h5.m-team.cc" | "kp.m-team.cc" | "next.m-team.cc" | "ob.m-team.cc"
        | "pt.m-team.cc" | "tp.m-team.cc" | "xp.m-team.cc" | "xp.m-team.io" | "zp.m-team.io" => {
            Some("mteam")
        }
        "musopia.vip" | "pt.xzt.me" => Some("musopia"),
        "pt.muxuege.org" => Some("muxuege"),
        "myanonamouse.net" => Some("myanonamouse"),
        "cc.mypt.cc" => Some("mypt"),
        "nanyangpt.com" => Some("nanyangpt"),
        "ncore.pro" => Some("ncore"),
        "nebulance.io" => Some("nebulance"),
        "nekobt.to" => Some("nekobt"),
        "bt.neu6.edu.cn" => Some("neu6"),
        "nexushd.org" | "v6.nexushd.org" => Some("nexushd"),
        "nicept.net" => Some("nicept"),
        "njtupt.top" => Some("njtupt"),
        "nordicbytes.org" => Some("nordicbytes"),
        "nordicq.org" => Some("nordicquality"),
        "pt.novahd.top" => Some("novahd"),
        "npupt.com" => Some("npupt"),
        "pt.nwsuaf6.edu.cn" => Some("nwsuaf6"),
        "nyaa.si" | "sukebei.nyaa.si" => Some("nyaa"),
        "okpt.net" => Some("okpt"),
        "oldtoons.world" => Some("oldtoonsworld"),
        "onlyencodes.cc" => Some("onlyencodes"),
        "open.cd" | "check.open.cd" => Some("opencd"),
        "oppaiti.me" => Some("oppaiti"),
        "orpheus.network" => Some("orpheus"),
        "oshen.win" => Some("oshenpt"),
        "ourbits.club" | "pt.ourhelp.club" => Some("ourbits"),
        "pandapt.net" => Some("pandapt"),
        "passthepopcorn.me" => Some("passthepopcorn"),
        "piggo.me" => Some("piggo"),
        "pixelcove.me" => Some("pixelcove"),
        "playlet.cc" | "playletpt.xyz" => Some("playletpt"),
        "pornbay.org" => Some("pornbay"),
        "pornbits.net" | "pornbits.org" => Some("pornbits"),
        "pornolab.net" => Some("pornolab"),
        "portugas.org" => Some("portugas"),
        "privatehd.to" => Some("privatehd"),
        "pt.j99.info" => Some("pt99"),
        "ptcafe.club" => Some("ptcafe"),
        "ptchina.org" => Some("ptchina"),
        "plus.ptdream.net" | "ptdream.net" => Some("ptdream"),
        "pter.club" | "pterclub.com" | "pterclub.net" => Some("pter"),
        "cusat.win" | "ptfans.cc" => Some("ptfans"),
        "pt.gtk.pw" | "pt.gtkpw.xyz" => Some("ptgtk"),
        "pthome.net" => Some("pthome"),
        "ptlao.top" => Some("ptlao"),
        "ptlgs.org" => Some("ptlgs"),
        "ptlsp.com" => Some("ptlsp"),
        "pt.msg.vg" => Some("ptmsg"),
        "ptneko.com" => Some("ptneko"),
        "ptsbao.club" => Some("ptsbao"),
        "ptskit.org" => Some("ptskit"),
        "pttime.org" => Some("pttime"),
        "ptvicomo.net" => Some("ptvicomo"),
        "ptzone.xyz" => Some("ptzone"),
        "pussytorrents.org" => Some("pussytorrents"),
        "qingwa.pro" | "qingwapt.com" | "qingwapt.org" => Some("qingwa"),
        "hitpt.org" => Some("qingyingpt"),
        "bilibili.download" => Some("railgunpt"),
        "raingfh.top" => Some("raingfh"),
        "redacted.ch" | "redacted.sh" => Some("redacted"),
        "leaves.red" => Some("redleaves"),
        "reelflix.cc" | "reelflix.xyz" => Some("reelflix"),
        "retroflix.club" | "retroflix.net" => Some("retroflix"),
        "retrotoon.world" => Some("retrotoon"),
        "rousi.zip" => Some("rousi"),
        "rousi.pro" => Some("rousipro"),
        "resource.xidian.edu.cn" => Some("rs"),
        "rutracker.net" | "rutracker.nl" | "rutracker.org" => Some("rutracker"),
        "sanpro.pw" => Some("sanpro"),
        "sbpt.link" => Some("sbpt"),
        "sdbits.org" => Some("sdbits"),
        "secret-cinema.pw" => Some("secretcinema"),
        "seedpool.org" => Some("seedpool"),
        "sewerpt.com" => Some("sewerpt"),
        "shareisland.org" => Some("shareisland"),
        "sharkpt.net" => Some("sharkpt"),
        "simurg.world" => Some("simurg"),
        "si-qi.xyz" => Some("siqi"),
        "pt.sjtu.edu.cn" => Some("sjtu"),
        "skyey2.com" | "skyeysnow.com" => Some("skyeysnow"),
        "snakepop.art" => Some("snakepop"),
        "pt.soulvoice.club" => Some("soulvoice"),
        "icetorrent.org" | "myxz.eu" | "scenefz.me" | "speedapp.io" | "u-torrents.ro" => {
            Some("speedapp")
        }
        "sportscult.org" => Some("sportscult"),
        "hdcmct.org" | "springsunday.net" => Some("springsunday"),
        "shadowflow.org" | "star-space.net" => Some("starspace"),
        "sts.tw" => Some("stspt"),
        "sugoimusic.me" => Some("sugoimusic"),
        "sunnypt.top" => Some("sunnypt"),
        "superbits.org" => Some("superbits"),
        "tangpt.top" => Some("tangpt"),
        "et8.org" => Some("tccf"),
        "telly.wtf" => Some("telly"),
        "pt.tey.cc" => Some("tey"),
        "thegeeks.click" => Some("thegeeks"),
        "thevault.click" => Some("thevault"),
        "tjupt.org" => Some("tjupt"),
        "pt.eastgame.org" => Some("tlfbits"),
        "tmpt.top" => Some("tmpt"),
        "tokyopt.xyz" => Some("tokyopt"),
        "tokyo-tosho.net" | "tokyotosho.info" | "tokyotosho.se" => Some("tokyotosho"),
        "torrenthub.club" => Some("torrenthub"),
        "tleechreload.org" | "tlgetin.cc" | "torrentleech.cc" | "torrentleech.me"
        | "torrentleech.org" => Some("torrentleech"),
        "torrents-csv.com" | "torrents-csv.ml" => Some("torrentscsv"),
        "torrentseeds.org" => Some("torrentseeds"),
        "t.tosky.club" => Some("tosky"),
        "totheglory.im" => Some("totheglory"),
        "pt.tu88.men" => Some("tu88"),
        "u2.dmhy.org" => Some("u2"),
        "ubits.club" => Some("ubits"),
        "uhdbits.org" => Some("uhdbits"),
        "ultrahd.net" => Some("ultrahd"),
        "upload.cx" => Some("uploadcx"),
        "pt.vclib.online" => Some("vclib"),
        "whu.pt" => Some("whupt"),
        "wintersakura.net" => Some("wintersakura"),
        "wukongwendao.top" => Some("wukongwendao"),
        "pt.xauat6.edu.cn" => Some("xauat6"),
        "xinglin.one" | "xingtan.one" => Some("xingtan"),
        "xingwan.cc" => Some("xingwan"),
        "pt.xingyungept.cn" | "pt.xingyungept.org" | "xingyunge.top" => Some("xingyunge"),
        "pt.hdbd.us" => Some("ydypt"),
        "yemapt.org" => Some("yemapt"),
        "yingk.com" => Some("yingk"),
        "pt.ying.us.kg" => Some("yinguskg"),
        "yu-scene.net" => Some("yuscene"),
        "bbs.yzyy.asia" | "yzyy.org" => Some("yzyy"),
        "pt.zhixing.bjtu.edu.cn" => Some("zhixing"),
        "zhuque.in" => Some("zhuque"),
        "zmpt.cc" => Some("zmpt"),
        "zrpt.cc" => Some("zrpt"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_current_and_legacy_ptd_hosts() {
        assert_eq!(site_id_for_host("kp.m-team.cc"), Some("mteam"));
        assert_eq!(site_id_for_host("chdbits.co"), Some("chdbits"));
        assert_eq!(site_id_for_host("www.chdbits.co"), Some("chdbits"));
        assert_eq!(site_id_for_host("tracker.invalid"), None);
    }
}
