//! PT-Depiler site presets supported by the rflush adapters.
//!
//! Generated from PT-Depiler site definitions at commit
//! `e9fae952f8200ed06a0822baae6f6f6ae84b2f5a` (2026-08-31).

use serde::Serialize;

#[derive(Debug, Clone, Copy, Serialize)]
pub struct PtdSitePreset {
    pub ptd_id: &'static str,
    pub name: &'static str,
    pub site_type: &'static str,
    pub base_url: &'static str,
    pub aliases: &'static [&'static str],
}

pub const SITE_PRESETS: &[PtdSitePreset] = &[
    PtdSitePreset {
        ptd_id: "13city",
        name: "13city",
        site_type: "nexusphp",
        base_url: "https://13city.org",
        aliases: &["13城"],
    },
    PtdSitePreset {
        ptd_id: "1ptba",
        name: "1PTBar",
        site_type: "nexusphp",
        base_url: "https://1ptba.com",
        aliases: &["壹PT"],
    },
    PtdSitePreset {
        ptd_id: "2xfree",
        name: "2xFree",
        site_type: "nexusphp",
        base_url: "https://pt.2xfree.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "52movie",
        name: "52movie",
        site_type: "nexusphp",
        base_url: "https://www.52movie.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "52pt",
        name: "52PT",
        site_type: "nexusphp",
        base_url: "https://52pt.site",
        aliases: &["我爱PT"],
    },
    PtdSitePreset {
        ptd_id: "afun",
        name: "Afun",
        site_type: "nexusphp",
        base_url: "https://www.ptlover.cc",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "agsvpt",
        name: "AGSVPT",
        site_type: "nexusphp",
        base_url: "https://pt.agsvpt.cn",
        aliases: &["末日种子库"],
    },
    PtdSitePreset {
        ptd_id: "alingpt",
        name: "alingPT",
        site_type: "nexusphp",
        base_url: "https://pt.aling.de",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "asmrpt",
        name: "ASMR PT",
        site_type: "nexusphp",
        base_url: "https://www.asmrpt.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "audiences",
        name: "Audiences",
        site_type: "nexusphp",
        base_url: "https://audiences.me",
        aliases: &["观众", "人人人"],
    },
    PtdSitePreset {
        ptd_id: "avgv",
        name: "爱薇网",
        site_type: "nexusphp",
        base_url: "https://avgv.cc",
        aliases: &["AVGV"],
    },
    PtdSitePreset {
        ptd_id: "azusa",
        name: "梓喵",
        site_type: "nexusphp",
        base_url: "https://azusa.wiki",
        aliases: &["Azusa"],
    },
    PtdSitePreset {
        ptd_id: "baozi",
        name: "包子",
        site_type: "nexusphp",
        base_url: "https://p.t-baozi.cc",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "beitai",
        name: "备胎",
        site_type: "nexusphp",
        base_url: "https://www.beitai.pt",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "btschool",
        name: "BTSCHOOL",
        site_type: "nexusphp",
        base_url: "https://pt.btschool.club",
        aliases: &["学校"],
    },
    PtdSitePreset {
        ptd_id: "byrbt",
        name: "北邮人-BYRBT",
        site_type: "nexusphp",
        base_url: "https://byr.pt",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "carpt",
        name: "CarPT",
        site_type: "nexusphp",
        base_url: "https://carpt.net",
        aliases: &["车PT", "车站"],
    },
    PtdSitePreset {
        ptd_id: "cbg",
        name: "藏宝阁",
        site_type: "nexusphp",
        base_url: "https://cangbao.ge",
        aliases: &["藏宝阁", "cbg", "CangBaoGe"],
    },
    PtdSitePreset {
        ptd_id: "cdfile",
        name: "CD File",
        site_type: "nexusphp",
        base_url: "https://pt.cdfile.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "cdy",
        name: "传道院",
        site_type: "nexusphp",
        base_url: "https://pt.cdy.pics",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "chdbits",
        name: "CHDBits",
        site_type: "nexusphp",
        base_url: "https://ptchdbits.co",
        aliases: &["彩虹岛", "CHD"],
    },
    PtdSitePreset {
        ptd_id: "cnscg",
        name: "圣城家园PT",
        site_type: "nexusphp",
        base_url: "https://www.cnscg.club",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "crabpt",
        name: "CrabPt",
        site_type: "nexusphp",
        base_url: "https://crabpt.vip",
        aliases: &["蟹黄堡"],
    },
    PtdSitePreset {
        ptd_id: "cspt",
        name: "财神",
        site_type: "nexusphp",
        base_url: "https://cspt.top",
        aliases: &["CSPT"],
    },
    PtdSitePreset {
        ptd_id: "cyanbug",
        name: "CyanBug",
        site_type: "nexusphp",
        base_url: "https://cyanbug.net",
        aliases: &["大青虫"],
    },
    PtdSitePreset {
        ptd_id: "dajiao",
        name: "DAJIAO",
        site_type: "nexusphp",
        base_url: "https://dajiao.cyou",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "daxiangjiao",
        name: "DaXiangJiao",
        site_type: "nexusphp",
        base_url: "https://pt.daxiangjiao.org",
        aliases: &["大象蕉"],
    },
    PtdSitePreset {
        ptd_id: "dhtclub",
        name: "DHTCLUB PT",
        site_type: "nexusphp",
        base_url: "https://pt.dhtclub.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "discfan",
        name: "DiscFan",
        site_type: "nexusphp",
        base_url: "https://discfan.net",
        aliases: &["碟粉"],
    },
    PtdSitePreset {
        ptd_id: "dragonhd",
        name: "龍之家",
        site_type: "nexusphp",
        base_url: "https://www.dragonhd.xyz",
        aliases: &["DragonHD"],
    },
    PtdSitePreset {
        ptd_id: "dstudio",
        name: "Depth Studio",
        site_type: "nexusphp",
        base_url: "https://dstudio.me",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "dubhe",
        name: "天枢",
        site_type: "nexusphp",
        base_url: "https://dubhe.site",
        aliases: &["Dubhe"],
    },
    PtdSitePreset {
        ptd_id: "ecustpt",
        name: "ECUSTPT",
        site_type: "nexusphp",
        base_url: "https://pt.ecust.pp.ua",
        aliases: &["花梨月下"],
    },
    PtdSitePreset {
        ptd_id: "fhpt",
        name: "凤凰PT",
        site_type: "nexusphp",
        base_url: "https://pt.521.best",
        aliases: &["FengHuang PT", "521best"],
    },
    PtdSitePreset {
        ptd_id: "filept",
        name: "Filept",
        site_type: "nexusphp",
        base_url: "https://www.filept.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "freefarm",
        name: "自由农场",
        site_type: "nexusphp",
        base_url: "https://pt.0ff.cc",
        aliases: &["FreeFarm", "Farmm"],
    },
    PtdSitePreset {
        ptd_id: "gainbound",
        name: "丐帮",
        site_type: "nexusphp",
        base_url: "https://gainbound.net",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ggpt",
        name: "GGPT",
        site_type: "nexusphp",
        base_url: "https://www.gamegamept.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "haidan",
        name: "海胆",
        site_type: "nexusphp",
        base_url: "https://www.haidan.cc",
        aliases: &["海胆之家", "HaiDan"],
    },
    PtdSitePreset {
        ptd_id: "hares",
        name: "HaresClub",
        site_type: "nexusphp",
        base_url: "https://club.hares.top",
        aliases: &["白兔", "白兔俱乐部"],
    },
    PtdSitePreset {
        ptd_id: "hd4fans",
        name: "HD4FANS",
        site_type: "nexusphp",
        base_url: "https://pt.hd4fans.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hdai",
        name: "HDAI",
        site_type: "nexusphp",
        base_url: "https://www.hd.ai",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hdarea",
        name: "HDArea",
        site_type: "nexusphp",
        base_url: "https://hdarea.club",
        aliases: &["高清视界", "好大"],
    },
    PtdSitePreset {
        ptd_id: "hdatmos",
        name: "HDATMOS",
        site_type: "nexusphp",
        base_url: "https://hdatmos.club",
        aliases: &["阿童木"],
    },
    PtdSitePreset {
        ptd_id: "hdbao",
        name: "HDBao",
        site_type: "nexusphp",
        base_url: "https://hdbao.cc",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hdchina",
        name: "HDChina",
        site_type: "nexusphp",
        base_url: "https://hdchina.org",
        aliases: &["瓷器"],
    },
    PtdSitePreset {
        ptd_id: "hdcity",
        name: "HDCity",
        site_type: "nexusphp",
        base_url: "https://hdcity.city",
        aliases: &["城市"],
    },
    PtdSitePreset {
        ptd_id: "hdclone",
        name: "HDClone",
        site_type: "nexusphp",
        base_url: "https://pt.hdclone.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hddisk",
        name: "HDDisk",
        site_type: "nexusphp",
        base_url: "https://hddisk.org",
        aliases: &["HDD"],
    },
    PtdSitePreset {
        ptd_id: "hddolby",
        name: "HD Dolby",
        site_type: "nexusphp",
        base_url: "https://www.hddolby.com",
        aliases: &["高清杜比"],
    },
    PtdSitePreset {
        ptd_id: "hdfans",
        name: "HDFans",
        site_type: "nexusphp",
        base_url: "https://hdfans.org",
        aliases: &["红豆饭"],
    },
    PtdSitePreset {
        ptd_id: "hdhome",
        name: "HDHome",
        site_type: "nexusphp",
        base_url: "https://hdhome.org",
        aliases: &["家园"],
    },
    PtdSitePreset {
        ptd_id: "hdkylin",
        name: "HDKylin",
        site_type: "nexusphp",
        base_url: "https://www.hdkyl.in",
        aliases: &["麒麟"],
    },
    PtdSitePreset {
        ptd_id: "hdmayi",
        name: "HDmayi",
        site_type: "nexusphp",
        base_url: "http://hdmayi.com",
        aliases: &["小蚂蚁PT", "XiaoMayi"],
    },
    PtdSitePreset {
        ptd_id: "hdpt",
        name: "明教",
        site_type: "nexusphp",
        base_url: "https://hdpt.xyz",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hdsky",
        name: "HDSky",
        site_type: "nexusphp",
        base_url: "https://hdsky.me",
        aliases: &["HDS", "天空"],
    },
    PtdSitePreset {
        ptd_id: "hdstreet",
        name: "高清街",
        site_type: "nexusphp",
        base_url: "https://hdstreet.club",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hdtime",
        name: "HDTime",
        site_type: "nexusphp",
        base_url: "https://hdtime.org",
        aliases: &["时间", "时光"],
    },
    PtdSitePreset {
        ptd_id: "hdupt",
        name: "HDU",
        site_type: "nexusphp",
        base_url: "https://pt.hdupt.com",
        aliases: &["好多油"],
    },
    PtdSitePreset {
        ptd_id: "hdvideo",
        name: "HDVideo",
        site_type: "nexusphp",
        base_url: "https://hdvideo.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hdzone",
        name: "HDZone",
        site_type: "nexusphp",
        base_url: "https://hdfun.me",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hhanclub",
        name: "憨憨",
        site_type: "nexusphp",
        base_url: "https://hhanclub.net",
        aliases: &["HHanClub"],
    },
    PtdSitePreset {
        ptd_id: "hitpt",
        name: "百川PT",
        site_type: "nexusphp",
        base_url: "https://www.hitpt.com",
        aliases: &["百川PT"],
    },
    PtdSitePreset {
        ptd_id: "hspt",
        name: "回声PT",
        site_type: "nexusphp",
        base_url: "https://hspt.club",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "htpt",
        name: "海棠PT",
        site_type: "nexusphp",
        base_url: "https://www.htpt.cc",
        aliases: &["海棠曲艺园", "海棠"],
    },
    PtdSitePreset {
        ptd_id: "hudbt",
        name: "蝴蝶-HUDBT",
        site_type: "nexusphp",
        base_url: "https://hudbt.hust.edu.cn",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "hxpt",
        name: "好学",
        site_type: "nexusphp",
        base_url: "https://www.hxpt.org",
        aliases: &["HXPT"],
    },
    PtdSitePreset {
        ptd_id: "icc2022",
        name: "ICC",
        site_type: "nexusphp",
        base_url: "https://www.icc2022.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ihdbits",
        name: "iHDBits",
        site_type: "nexusphp",
        base_url: "http://ihdbits.me",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ilolicon",
        name: "ilolicon",
        site_type: "nexusphp",
        base_url: "https://mua.xloli.cc",
        aliases: &["爱萝莉"],
    },
    PtdSitePreset {
        ptd_id: "itzmx",
        name: "PT分享站",
        site_type: "nexusphp",
        base_url: "https://pt.itzmx.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "joyhd",
        name: "JoyHD",
        site_type: "nexusphp",
        base_url: "https://www.joyhd.net",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "kamept",
        name: "KamePT",
        site_type: "nexusphp",
        base_url: "https://kamept.com",
        aliases: &["龟站"],
    },
    PtdSitePreset {
        ptd_id: "keepfrds",
        name: "PT@KEEPFRDS",
        site_type: "nexusphp",
        base_url: "https://pt.keepfrds.com",
        aliases: &["FRDS", "朋友"],
    },
    PtdSitePreset {
        ptd_id: "kelu",
        name: "Kelu",
        site_type: "nexusphp",
        base_url: "https://our.kelu.one",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "kufei",
        name: "库非",
        site_type: "nexusphp",
        base_url: "https://kufei.org",
        aliases: &["Kufei"],
    },
    PtdSitePreset {
        ptd_id: "kunlun",
        name: "昆仑",
        site_type: "nexusphp",
        base_url: "https://www.yhpp.cc",
        aliases: &["Kunlun", "YHPP"],
    },
    PtdSitePreset {
        ptd_id: "lajidui",
        name: "lajidui",
        site_type: "nexusphp",
        base_url: "https://pt.lajidui.top",
        aliases: &["垃圾堆"],
    },
    PtdSitePreset {
        ptd_id: "lemonhd",
        name: "LemonHD",
        site_type: "nexusphp",
        base_url: "https://lemonhd.club",
        aliases: &["柠檬不酸"],
    },
    PtdSitePreset {
        ptd_id: "lemonhdnet",
        name: "柠檬不甜",
        site_type: "nexusphp",
        base_url: "https://lemonhd.net",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "lemonhdorg",
        name: "LemonHD",
        site_type: "nexusphp",
        base_url: "https://lemonhd.org",
        aliases: &["柠檬"],
    },
    PtdSitePreset {
        ptd_id: "longpt",
        name: "LongPT",
        site_type: "nexusphp",
        base_url: "https://longpt.org",
        aliases: &["LongPT", "龙PT"],
    },
    PtdSitePreset {
        ptd_id: "luckpt",
        name: "LuckPT",
        site_type: "nexusphp",
        base_url: "https://pt.luckpt.de",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "march",
        name: "March-Media",
        site_type: "nexusphp",
        base_url: "https://duckboobee.org",
        aliases: &["三月传媒"],
    },
    PtdSitePreset {
        ptd_id: "moecat",
        name: "MoeCat",
        site_type: "nexusphp",
        base_url: "https://moecat.best",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "momentpt",
        name: "MomentPT",
        site_type: "nexusphp",
        base_url: "https://www.momentpt.top",
        aliases: &["瞬间"],
    },
    PtdSitePreset {
        ptd_id: "mteam",
        name: "M-Team - TP",
        site_type: "mteam",
        base_url: "https://api.m-team.cc",
        aliases: &["MTeam", "馒头"],
    },
    PtdSitePreset {
        ptd_id: "musopia",
        name: "音乐乌托邦",
        site_type: "nexusphp",
        base_url: "https://www.musopia.vip",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "muxuege",
        name: "慕雪阁",
        site_type: "nexusphp",
        base_url: "https://pt.muxuege.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "mypt",
        name: "MyPT",
        site_type: "nexusphp",
        base_url: "https://cc.mypt.cc",
        aliases: &["我的PT"],
    },
    PtdSitePreset {
        ptd_id: "nanyangpt",
        name: "南洋PT",
        site_type: "nexusphp",
        base_url: "https://nanyangpt.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "neu6",
        name: "六维空间",
        site_type: "nexusphp",
        base_url: "http://bt.neu6.edu.cn",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "nexushd",
        name: "NexusHD",
        site_type: "nexusphp",
        base_url: "https://v6.nexushd.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "nicept",
        name: "NicePT",
        site_type: "nexusphp",
        base_url: "https://www.nicept.net",
        aliases: &["老师"],
    },
    PtdSitePreset {
        ptd_id: "njtupt",
        name: "浦园",
        site_type: "nexusphp",
        base_url: "https://njtupt.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "novahd",
        name: "NovaHD",
        site_type: "nexusphp",
        base_url: "https://pt.novahd.top",
        aliases: &["星云"],
    },
    PtdSitePreset {
        ptd_id: "npupt",
        name: "NPUBits",
        site_type: "nexusphp",
        base_url: "https://npupt.com",
        aliases: &["蒲公英"],
    },
    PtdSitePreset {
        ptd_id: "nwsuaf6",
        name: "麦田PT",
        site_type: "nexusphp",
        base_url: "https://pt.nwsuaf6.edu.cn",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "okpt",
        name: "OKPT",
        site_type: "nexusphp",
        base_url: "https://www.okpt.net",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "opencd",
        name: "OpenCD",
        site_type: "nexusphp",
        base_url: "https://open.cd",
        aliases: &["皇后"],
    },
    PtdSitePreset {
        ptd_id: "oshenpt",
        name: "OshenPT",
        site_type: "nexusphp",
        base_url: "https://www.oshen.win",
        aliases: &["奥申"],
    },
    PtdSitePreset {
        ptd_id: "ourbits",
        name: "OurBits",
        site_type: "nexusphp",
        base_url: "https://ourbits.club",
        aliases: &["我堡", "OB"],
    },
    PtdSitePreset {
        ptd_id: "pandapt",
        name: "PandaPT",
        site_type: "nexusphp",
        base_url: "https://pandapt.net",
        aliases: &["熊猫高清"],
    },
    PtdSitePreset {
        ptd_id: "piggo",
        name: "Piggo",
        site_type: "nexusphp",
        base_url: "https://piggo.me",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "playletpt",
        name: "PlayLet",
        site_type: "nexusphp",
        base_url: "https://playlet.cc",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "pt99",
        name: "PT99",
        site_type: "nexusphp",
        base_url: "https://pt.j99.info",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ptcafe",
        name: "咖啡",
        site_type: "nexusphp",
        base_url: "https://ptcafe.club",
        aliases: &["PTCafe", "咖啡PT"],
    },
    PtdSitePreset {
        ptd_id: "ptchina",
        name: "PTChina",
        site_type: "nexusphp",
        base_url: "https://ptchina.org",
        aliases: &["铂金学院"],
    },
    PtdSitePreset {
        ptd_id: "ptdream",
        name: "PTDream",
        site_type: "nexusphp",
        base_url: "https://www.ptdream.net",
        aliases: &["PT梦想"],
    },
    PtdSitePreset {
        ptd_id: "pter",
        name: "PTer",
        site_type: "nexusphp",
        base_url: "https://pterclub.net",
        aliases: &["PTerClub", "猫站"],
    },
    PtdSitePreset {
        ptd_id: "ptfans",
        name: "PTFans",
        site_type: "nexusphp",
        base_url: "https://ptfans.cc",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ptgtk",
        name: "PT GTK",
        site_type: "nexusphp",
        base_url: "https://pt.gtkpw.xyz",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "pthome",
        name: "PTHome",
        site_type: "nexusphp",
        base_url: "https://pthome.net",
        aliases: &["PT之家", "铂金家"],
    },
    PtdSitePreset {
        ptd_id: "ptlao",
        name: "PTLAO",
        site_type: "nexusphp",
        base_url: "https://ptlao.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ptlgs",
        name: "PTLGS",
        site_type: "nexusphp",
        base_url: "https://ptlgs.org",
        aliases: &["劳改所"],
    },
    PtdSitePreset {
        ptd_id: "ptlsp",
        name: "PTLSP",
        site_type: "nexusphp",
        base_url: "https://www.ptlsp.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ptmsg",
        name: "PTMSG",
        site_type: "nexusphp",
        base_url: "https://pt.msg.vg",
        aliases: &["马杀鸡"],
    },
    PtdSitePreset {
        ptd_id: "ptneko",
        name: "超科学PT喵",
        site_type: "nexusphp",
        base_url: "https://ptneko.com",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ptsbao",
        name: "PTSBao",
        site_type: "nexusphp",
        base_url: "https://ptsbao.club",
        aliases: &["烧包", "骚包"],
    },
    PtdSitePreset {
        ptd_id: "ptskit",
        name: "PTSkit",
        site_type: "nexusphp",
        base_url: "https://www.ptskit.org",
        aliases: &["拾刻"],
    },
    PtdSitePreset {
        ptd_id: "pttime",
        name: "PTTime",
        site_type: "nexusphp",
        base_url: "https://www.pttime.org",
        aliases: &["PT时间"],
    },
    PtdSitePreset {
        ptd_id: "ptvicomo",
        name: "象岛",
        site_type: "nexusphp",
        base_url: "https://ptvicomo.net",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ptzone",
        name: "PTzone",
        site_type: "nexusphp",
        base_url: "https://ptzone.xyz",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "qingyingpt",
        name: "清影PT",
        site_type: "nexusphp",
        base_url: "https://hitpt.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "railgunpt",
        name: "RailgunPT",
        site_type: "nexusphp",
        base_url: "https://bilibili.download",
        aliases: &["BILIBILI"],
    },
    PtdSitePreset {
        ptd_id: "raingfh",
        name: "雨",
        site_type: "nexusphp",
        base_url: "https://raingfh.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "redleaves",
        name: "红叶",
        site_type: "nexusphp",
        base_url: "https://leaves.red",
        aliases: &["RedLeaves"],
    },
    PtdSitePreset {
        ptd_id: "retroflix",
        name: "RetroFlix",
        site_type: "nexusphp",
        base_url: "https://retroflix.net",
        aliases: &["RF"],
    },
    PtdSitePreset {
        ptd_id: "rousi",
        name: "Rousi",
        site_type: "nexusphp",
        base_url: "https://rousi.zip",
        aliases: &["肉丝"],
    },
    PtdSitePreset {
        ptd_id: "rs",
        name: "睿思",
        site_type: "nexusphp",
        base_url: "https://resource.xidian.edu.cn",
        aliases: &["西电睿思"],
    },
    PtdSitePreset {
        ptd_id: "sbpt",
        name: "SBPT",
        site_type: "nexusphp",
        base_url: "https://sbpt.link",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "sewerpt",
        name: "下水道",
        site_type: "nexusphp",
        base_url: "https://sewerpt.com",
        aliases: &["SewerPT"],
    },
    PtdSitePreset {
        ptd_id: "sharkpt",
        name: "鲨鱼PT",
        site_type: "nexusphp",
        base_url: "https://sharkpt.net",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "siqi",
        name: "思齐",
        site_type: "nexusphp",
        base_url: "https://si-qi.xyz",
        aliases: &["SiQi"],
    },
    PtdSitePreset {
        ptd_id: "sjtu",
        name: "葡萄",
        site_type: "nexusphp",
        base_url: "https://pt.sjtu.edu.cn",
        aliases: &["PuTao", "SJTU"],
    },
    PtdSitePreset {
        ptd_id: "soulvoice",
        name: "SoulVoice",
        site_type: "nexusphp",
        base_url: "https://pt.soulvoice.club",
        aliases: &["聆音"],
    },
    PtdSitePreset {
        ptd_id: "springsunday",
        name: "SpringSunday",
        site_type: "nexusphp",
        base_url: "https://springsunday.net",
        aliases: &["CMCT", "SSD", "春天"],
    },
    PtdSitePreset {
        ptd_id: "stspt",
        name: "STSPT",
        site_type: "nexusphp",
        base_url: "https://www.sts.tw",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "tangpt",
        name: "躺平",
        site_type: "nexusphp",
        base_url: "https://www.tangpt.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "tccf",
        name: "TorrentCCF",
        site_type: "nexusphp",
        base_url: "https://et8.org",
        aliases: &["TCCF", "ET8"],
    },
    PtdSitePreset {
        ptd_id: "tey",
        name: "tey",
        site_type: "nexusphp",
        base_url: "https://pt.tey.cc",
        aliases: &["太乙"],
    },
    PtdSitePreset {
        ptd_id: "tjupt",
        name: "北洋园PT",
        site_type: "nexusphp",
        base_url: "https://tjupt.org",
        aliases: &["北洋园"],
    },
    PtdSitePreset {
        ptd_id: "tlfbits",
        name: "TLFBits",
        site_type: "nexusphp",
        base_url: "https://pt.eastgame.org",
        aliases: &["TLF Bits", "The Last Fantasy", "TLF", "吐鲁番"],
    },
    PtdSitePreset {
        ptd_id: "tmpt",
        name: "唐门",
        site_type: "nexusphp",
        base_url: "https://tmpt.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "tokyopt",
        name: "Tokyo",
        site_type: "nexusphp",
        base_url: "https://www.tokyopt.xyz",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "torrenthub",
        name: "TorrentHub",
        site_type: "nexusphp",
        base_url: "https://torrenthub.club",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "tosky",
        name: "ToSky",
        site_type: "nexusphp",
        base_url: "https://t.tosky.club",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "tu88",
        name: "TU88",
        site_type: "nexusphp",
        base_url: "https://pt.tu88.men",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "u2",
        name: "U2",
        site_type: "nexusphp",
        base_url: "https://u2.dmhy.org",
        aliases: &["幼儿园"],
    },
    PtdSitePreset {
        ptd_id: "ubits",
        name: "UBits",
        site_type: "nexusphp",
        base_url: "https://ubits.club",
        aliases: &["UB", "U堡"],
    },
    PtdSitePreset {
        ptd_id: "ultrahd",
        name: "UltraHD",
        site_type: "nexusphp",
        base_url: "https://ultrahd.net",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "vclib",
        name: "VC-Lib",
        site_type: "nexusphp",
        base_url: "https://pt.vclib.online",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "whupt",
        name: "珞樱-WHUPT",
        site_type: "nexusphp",
        base_url: "https://whu.pt",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "wintersakura",
        name: "WinterSakura",
        site_type: "nexusphp",
        base_url: "https://wintersakura.net",
        aliases: &["冬樱"],
    },
    PtdSitePreset {
        ptd_id: "wukongwendao",
        name: "悟空问道",
        site_type: "nexusphp",
        base_url: "https://wukongwendao.top",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "xauat6",
        name: "溪涧草堂PT",
        site_type: "nexusphp",
        base_url: "http://pt.xauat6.edu.cn",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "xingtan",
        name: "杏坛",
        site_type: "nexusphp",
        base_url: "https://xingtan.one",
        aliases: &["杏林", "XingTan"],
    },
    PtdSitePreset {
        ptd_id: "xingwan",
        name: "星湾",
        site_type: "nexusphp",
        base_url: "https://xingwan.cc",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "xingyunge",
        name: "星陨阁",
        site_type: "nexusphp",
        base_url: "https://pt.xingyungept.org",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "ydypt",
        name: "伊甸园",
        site_type: "nexusphp",
        base_url: "https://pt.hdbd.us",
        aliases: &[],
    },
    PtdSitePreset {
        ptd_id: "yingk",
        name: "影客",
        site_type: "nexusphp",
        base_url: "https://yingk.com",
        aliases: &["影客PT", "YingkPT", "美盒子", "MeiHeZi"],
    },
    PtdSitePreset {
        ptd_id: "yinguskg",
        name: "樱花",
        site_type: "nexusphp",
        base_url: "https://pt.ying.us.kg",
        aliases: &["YingUSKG", "ying.us.kg", "Ying"],
    },
    PtdSitePreset {
        ptd_id: "zmpt",
        name: "织梦",
        site_type: "nexusphp",
        base_url: "https://zmpt.cc",
        aliases: &["织梦PT", "ZMPT"],
    },
    PtdSitePreset {
        ptd_id: "zrpt",
        name: "ZRPT",
        site_type: "nexusphp",
        base_url: "https://zrpt.cc",
        aliases: &["探索自然美", "专注纪录片"],
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exposes_only_site_types_supported_by_rflush() {
        assert_eq!(SITE_PRESETS.len(), 164);
        assert!(
            SITE_PRESETS
                .iter()
                .all(|site| matches!(site.site_type, "nexusphp" | "mteam"))
        );
        let mteam = SITE_PRESETS
            .iter()
            .find(|site| site.ptd_id == "mteam")
            .unwrap();
        assert_eq!(mteam.base_url, "https://api.m-team.cc");
    }
}
