//! PTD level names and IDs for the verified user-statistics adapters.
//! Source: pt-plugins/PT-depiler e9fae952f8200ed06a0822baae6f6f6ae84b2f5a.

pub fn level_id(site: &str, name: &str) -> Option<i64> {
    let levels: &[(i64, &[&str])] = match site {
        "greatposterwall" => &[
            (0, &["User"]),
            (1, &["Member"]),
            (2, &["Power User"]),
            (3, &["Elite"]),
            (4, &["Torrent Master"]),
            (5, &["Power Torrent Master", "Power TM"]),
            (6, &["Elite Torrent Master", "Elite TM"]),
            (7, &["Guru"]),
        ],
        "opencd" => &[
            (1, &["User", "採女-正八品"]),
            (2, &["Power User", "常在-正七品"]),
            (3, &["Elite User", "贵人-正六品"]),
            (4, &["Crazy User", "良媛-正五品"]),
            (5, &["Insane User", "容华-正四品"]),
            (6, &["Veteran User", "贵嫔-正三品"]),
            (7, &["Extreme User", "淑仪-正二品"]),
            (8, &["Ultimate User", "贵妃-正一品"]),
            (9, &["Nexus Master", "皇后"]),
            (100, &["貴賓(VIP)"]),
            (101, &["養老族", "养老族"]),
            (201, &["保種員", "保种员"]),
            (202, &["發布員", "发布员"]),
            (203, &["工作人員"]),
            (204, &["管理员"]),
            (205, &["論壇版主", "论坛版主"]),
            (206, &["總版主", "总版主"]),
            (207, &["維護開发員"]),
        ],
        "baozi" => &[
            (1, &["Peasant"]),
            (2, &["User"]),
            (3, &["Power User"]),
            (4, &["Elite User"]),
            (5, &["Crazy User"]),
            (6, &["Insane User"]),
            (7, &["Veteran User"]),
            (8, &["Extreme User"]),
            (9, &["Ultimate User"]),
            (10, &["Nexus Master"]),
            (100, &["贵宾(VIP)"]),
            (200, &["养老族(Retiree)"]),
            (201, &["发布员(Uploader)"]),
            (202, &["总版主(Moderator)"]),
            (203, &["管理员(Administrator)"]),
            (204, &["维护开发员(Sysop)"]),
            (205, &["主管(Staff Leader)"]),
        ],
        "daxiangjiao" => &[
            (1, &["Peasant"]),
            (2, &["User"]),
            (3, &["Power User"]),
            (4, &["Elite User"]),
            (5, &["Crazy User"]),
            (6, &["Insane User"]),
            (7, &["Veteran User"]),
            (8, &["Extreme User"]),
            (9, &["Ultimate User"]),
            (10, &["Nexus Master"]),
            (100, &["VIP", "贵宾", "贵宾(VIP)"]),
            (200, &["Retiree", "养老族", "养老族(Retiree)"]),
            (201, &["Uploader", "发布员", "发布员(Uploader)"]),
            (202, &["Moderator", "总版主", "总版主(Moderator)"]),
            (203, &["Administrator", "管理员", "管理员(Administrator)"]),
            (204, &["Sysop", "维护开发员", "维护开发员(Sysop)"]),
            (205, &["Staff Leader", "主管", "主管(Staff Leader)"]),
        ],
        "dstudio" => &[
            (1, &["Peasant"]),
            (2, &["User"]),
            (3, &["Power User"]),
            (4, &["Elite User"]),
            (5, &["Crazy User"]),
            (6, &["Insane User"]),
            (7, &["Veteran User"]),
            (8, &["Extreme User"]),
            (9, &["Ultimate User"]),
            (10, &["Nexus Master"]),
            (100, &["贵宾(VIP)"]),
            (200, &["养老族(Retiree)"]),
            (201, &["发布员(Uploader)"]),
            (202, &["总版主(Moderator)"]),
            (203, &["管理员(Administrator)"]),
            (204, &["维护开发员(Sysop)"]),
            (205, &["主管(Staff Leader)"]),
        ],
        "ggpt" => &[
            (0, &["User"]),
            (1, &["Power User"]),
            (2, &["Elite User"]),
            (3, &["Crazy User"]),
            (4, &["Insane User"]),
            (5, &["Veteran User"]),
            (6, &["Extreme User"]),
            (7, &["Ultimate User"]),
            (8, &["Nexus Master"]),
            (9, &["养老族(Retiree)", "养老，散仙"]),
        ],
        "hdhome" => &[
            (1, &["User", "临时演员"]),
            (2, &["Power User", "跑龙套"]),
            (3, &["Elite User", "配角"]),
            (4, &["Crazy User", "主演"]),
            (5, &["Insane User", "领衔主演"]),
            (6, &["Veteran User", "明星"]),
            (7, &["Extreme User", "国际大腕"]),
            (8, &["Ultimate User", "影帝"]),
            (9, &["Nexus Master", "终身影帝"]),
        ],
        "hhanclub" => &[
            (0, &["憨头憨脑 User"]),
            (1, &["憨声憨气 Power User"]),
            (2, &["憨态可掬 Elite User"]),
            (3, &["明姿憨憨 Crazy User"]),
            (4, &["裝憨打呆 Insane User"]),
            (5, &["憨状可掬 Veteran User"]),
            (6, &["憨痴可人 Extreme User"]),
            (7, &["憨笑如花 Ultimate User"]),
            (8, &["满面娇憨 Nexus Master"]),
        ],
        "ilolicon" => &[
            (1, &["平民"]),
            (2, &["初级魔法少女"]),
            (3, &["有点经验的魔法少女"]),
            (4, &["高级魔法少女"]),
            (5, &["疯狂魔法少女"]),
            (6, &["超级疯狂的魔法少女"]),
            (7, &["经验丰富的魔法少女"]),
            (8, &["极限魔法少女"]),
            (9, &["终极魔法少女"]),
            (10, &["尼克斯大师"]),
            (100, &["贵宾"]),
            (200, &["退休的魔法少女"]),
            (201, &["魔法释放者"]),
            (202, &["至高的魔法师"]),
            (203, &["顶级魔法少女"]),
            (204, &["维护魔法少女"]),
            (205, &["首席魔法少女"]),
        ],
        "musopia" => &[
            (1, &["Peasant"]),
            (2, &["User"]),
            (3, &["Power User"]),
            (4, &["Elite User"]),
            (5, &["Crazy User"]),
            (6, &["Insane User"]),
            (7, &["Veteran User"]),
            (8, &["Extreme User"]),
            (9, &["Ultimate User"]),
            (10, &["Nexus Master"]),
            (100, &["贵宾(VIP)"]),
            (200, &["养老族(Retiree)"]),
            (201, &["发布员(Uploader)"]),
            (202, &["总版主(Moderator)"]),
            (203, &["管理员(Administrator)"]),
            (204, &["维护开发员(Sysop)"]),
            (205, &["主管(Staff Leader)"]),
        ],
        "nicept" => &[
            (1, &["Peasant"]),
            (2, &["User"]),
            (3, &["Power User"]),
            (4, &["Elite User"]),
            (5, &["Crazy User"]),
            (6, &["Insane User"]),
            (7, &["Veteran User"]),
            (8, &["Extreme User"]),
            (9, &["Ultimate User"]),
            (10, &["Nexus Master"]),
            (100, &["VIP", "贵宾", "贵宾(VIP)"]),
            (200, &["Retiree", "养老族", "养老族(Retiree)"]),
            (201, &["Uploader", "发布员", "发布员(Uploader)"]),
            (202, &["Moderator", "总版主", "总版主(Moderator)"]),
            (203, &["Administrator", "管理员", "管理员(Administrator)"]),
            (204, &["Sysop", "维护开发员", "维护开发员(Sysop)"]),
            (205, &["Staff Leader", "主管", "主管(Staff Leader)"]),
        ],
        "novahd" => &[
            (0, &["User"]),
            (1, &["Power User"]),
            (2, &["Elite User"]),
            (3, &["Crazy User"]),
            (4, &["Insane User"]),
            (5, &["Veteran User"]),
            (6, &["Extreme User"]),
            (7, &["Ultimate User"]),
            (8, &["Nexus Master"]),
        ],
        "playletpt" => &[
            (0, &["User"]),
            (1, &["Power User"]),
            (2, &["Elite User"]),
            (3, &["Crazy User"]),
            (4, &["Insane User"]),
            (5, &["Veteran User"]),
            (6, &["Extreme User"]),
            (7, &["Ultimate User"]),
            (8, &["Nexus Master"]),
        ],
        "qingwa" => &[
            (0, &["Peasant", "青蛙卵"]),
            (1, &["User", "蝌蚪"]),
            (2, &["Power User", "幼蛙"]),
            (3, &["Elite User", "成蛙"]),
            (4, &["Crazy User", "妙蛙种子"]),
            (5, &["Insane User", "妙蛙草"]),
            (6, &["Veteran User", "妙蛙花"]),
            (7, &["Extreme User", "mega妙蛙花"]),
            (8, &["Ultimate User", "极巨化妙蛙花"]),
            (99, &["SVIP", "闪光妙蛙花"]),
            (100, &["VIP", "贵宾"]),
        ],
        "railgunpt" => &[
            // The profile still uses the default name for the initial rank.
            (0, &["Lv0", "User"]),
            (1, &["Lv1"]),
            (2, &["Lv2"]),
            (3, &["Lv3"]),
            (4, &["Lv4"]),
            (5, &["Lv5"]),
            (6, &["Lv6"]),
            (7, &["Lv7"]),
            (8, &["Lv8"]),
        ],
        "tangpt" => &[
            (1, &["Peasant"]),
            (2, &["User"]),
            (3, &["Power User"]),
            (4, &["Elite User"]),
            (5, &["Crazy User"]),
            (6, &["Insane User"]),
            (7, &["Veteran User"]),
            (8, &["Extreme User"]),
            (9, &["Ultimate User"]),
            (10, &["Nexus Master"]),
            (100, &["贵宾(VIP)"]),
            (200, &["养老族(Retiree)"]),
            (201, &["发布员(Uploader)"]),
            (202, &["总版主(Moderator)"]),
            (203, &["管理员(Administrator)"]),
            (204, &["维护开发员(Sysop)"]),
            (205, &["主管(Staff Leader)"]),
        ],
        "u2" => &[
            (0, &["异教徒"]),
            (1, &["路人"]),
            (2, &["御宅族"]),
            (3, &["宅修士"]),
            (4, &["宅教士"]),
            (5, &["宅传教士"]),
            (6, &["宅护法"]),
            (7, &["宅贤者"]),
            (8, &["宅圣"]),
            (9, &["宅神"]),
            (200, &["福音组"]),
            (201, &["现充"]),
            (202, &["FFF团"]),
            (203, &["执事"]),
            (204, &["司铎"]),
            (205, &["枢机"]),
            (206, &["站宗"]),
        ],
        "ubits" => &[
            (0, &["Peasant"]),
            (1, &["User"]),
            (2, &["Power User"]),
            (3, &["Elite User"]),
            (4, &["Crazy User"]),
            (5, &["Insane User"]),
            (6, &["Veteran User"]),
            (7, &["Extreme User"]),
            (8, &["Ultimate User"]),
            (9, &["Nexus Master"]),
            (10, &["贵宾(VIP)"]),
            (11, &["养老族(Retiree)"]),
        ],
        _ => return None,
    };
    let clean = |value: &str| {
        value
            .chars()
            .filter(|c| !c.is_whitespace() && *c != '_')
            .collect::<String>()
            .to_lowercase()
    };
    let name = clean(name);
    if name.is_empty() {
        return None;
    }
    levels
        .iter()
        .find(|(_, names)| {
            names
                .iter()
                .any(|candidate| clean(candidate).contains(&name))
        })
        .map(|(id, _)| *id)
}
#[cfg(test)]
mod tests {
    use super::level_id;
    #[test]
    fn site_specific_level_numbering_is_preserved() {
        assert_eq!(level_id("qingwa", "Power User"), Some(2));
        assert_eq!(level_id("nicept", "Power User"), Some(3));
        assert_eq!(level_id("hdhome", "User"), Some(1));
        assert_eq!(level_id("ggpt", "User"), Some(0));
        assert_eq!(level_id("u2", "御宅族"), Some(2));
        assert_eq!(level_id("ilolicon", "初级魔法少女"), Some(2));
        assert_eq!(level_id("unknown", "User"), None);
        assert_eq!(level_id("qingwa", ""), None);
    }
}
